# prod setting
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: ${DATABASE}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    
    # jpa 설정
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update        # DB 초기화 전략 (none, create, create-drop, update, validate(실서버)))
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                show-sql: true        # 쿼리 로그 출력
                format-sql: true      # 쿼리 로그 포맷 (정렬)